version: "3.7"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ".:/app"
    ports:
      - "5001:5001"
      - "5002:5002"
    depends_on:
      - db
  db:
    image: mariadb/server:10.3
    ports:
      - "5005:5005"
    volumes:
      - "./localdb:/var/lib/mysql/"
      - "./dbconf:/etc/mysql/conf.d"
    environment:
      MYSQL_DATABASE: "docker-practice-db"
      MYSQL_USER: "docker-practice-user"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "1234"